name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
        id: package
        with:
          pat: fake
          dryRun: true

      - uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          name: ${{ github.ref_name }}
          files: ${{ steps.package.outputs.vsixPath }}
          fail_on_unmatched_files: true
          draft: true

      - uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.package.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com

      - uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.package.outputs.vsixPath }}
